version: '3.9'
volumes:
  alice-volume:
  bob-volume:

services:
  alice:
    image: 'local/node-template'
    volumes:
      - 'alice-volume:/data'
    command:
      - "--alice"
      - "--chain=local"
      - '--validator'
      - '--rpc-cors=all'
      - '--unsafe-rpc-external'
      - '--rpc-methods=unsafe'
      - '--node-key=0000000000000000000000000000000000000000000000000000000000000001'
    ports:
      - '9944:9944'

  bob:
    image: 'local/node-template'
    depends_on:
      - alice
    volumes:
      - 'bob-volume:/data'
    command:
      - "--bob"
      - "--chain=local"
      - '--validator'
      - '--rpc-cors=all'
      - '--unsafe-rpc-external'
      - '--rpc-methods=unsafe'
      - '--bootnodes=/dns4/alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    ports:
      - '9945:9944'

