[relaychain]
default_image = "docker.io/parity/polkadot:latest"
default_command = "polkadot"

chain = "local"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true
